### ISSUE TITLE
Update gem version to follow API key changes

### ISSUE THREAD

**Issue by kiote** [ivanoblomov/google_maps_geocoder#5]
Hi Roderick!

Could you please update the gem itself, so it will have the changes I've added in https://github.com/ivanoblomov/google_maps_geocoder/pull/4?

I've tried to switch to "native" gem from my forked one, but found that it still not support new functionality yet.

Thanks!

**Comment by ivanoblomov** [comment]
Hey @kiote, sorry for the delay!

I took a couple days to make some improvements—some minor refactoring, documentation, and integration with rubocop and Coveralls—and bumped the gem to "0.4.0.pre1" with https://github.com/ivanoblomov/google_maps_geocoder/commit/4617a4d861842a100ad6ae63d138463e6ea17d41.

Take it out for a spin and let me know if we should make any changes before releasing officially. Cheers!

**Comment by kiote** [comment]
Hi @ivanoblomov! 

Sorry back for the delay :) but I've tested that bumped gem and found an error after ```require 'google_maps_geocoder'``` saying ```LoadError: cannot load such file -- google_maps_geocoder``` but with ```require 'google_maps_geocoder/google_maps_geocoder'``` seems to require fine.

Anyway think it's not a deliberate idea to change the require string that way, so that probably could be fixed?

Thanks!

**Comment by ivanoblomov** [comment]
@kiote just to clarify, the `require` line you had to fix was in your client code and <em>not</em> in the gem's code, right?

If so, this was intentional because the gem versioning utility I'm using requires namespacing in `lib/`. (See https://github.com/svenfuchs/gem-release for more info.)

**Comment by kiote** [comment]
Yes, it's require in the client, right.

So do you mean that's how things should be? Then it's okay finally :)

**Comment by ivanoblomov** [comment]
Right on, thanks again for contributing!
